// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CUIT
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            HtmlHyperlink uIModelAirplanesHyperlink = this.UIBingInternetExplorerWindow.UIHomeTailspinToysDocument.UIModelAirplanesCustom.UIModelAirplanesHyperlink;
            WinButton uICloseButton = this.UIBingInternetExplorerWindow.UIHomeTailspinToysInteTitleBar.UICloseButton;
            #endregion

            // Go to web page 'http://tailspinpaasdeploy.azurewebsites.net/' using new browser instance
            this.UIBingInternetExplorerWindow.LaunchUrl(new System.Uri(this.RecordedMethod1Params.UIBingInternetExplorerWindowUrl));

            // Click 'Model Airplanes' link
            Mouse.Click(uIModelAirplanesHyperlink, new Point(92, 22));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(33, 0));
        }
        
        /// <summary>
        /// RecordedMethod2 - Use 'RecordedMethod2Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchusinEdit = this.UINewtabInternetExplorWindow.UIAddressandsearchusinWindow.UIAddressandsearchusinEdit;
            WinEdit uIItemEdit = this.UINewtabInternetExplorWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Go to web page 'about:Tabs' using new browser instance
            this.UINewtabInternetExplorWindow.LaunchUrl(new System.Uri(this.RecordedMethod2Params.UINewtabInternetExplorWindowUrl));

            // Click 'Address and search using Bing' text box
            Mouse.Click(uIAddressandsearchusinEdit, new Point(241, 9));

            // Type 'http{RShiftKey}://tailspinpaasdeploy.azurewebsites' in text box
            Keyboard.SendKeys(uIItemEdit, this.RecordedMethod2Params.UIItemEditSendKeys, ModifierKeys.None);

            // Type '.net{Enter}' in text box
            Keyboard.SendKeys(uIItemEdit, this.RecordedMethod2Params.UIItemEditSendKeys1, ModifierKeys.None);
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public UIBingInternetExplorerWindow UIBingInternetExplorerWindow
        {
            get
            {
                if ((this.mUIBingInternetExplorerWindow == null))
                {
                    this.mUIBingInternetExplorerWindow = new UIBingInternetExplorerWindow();
                }
                return this.mUIBingInternetExplorerWindow;
            }
        }
        
        public UINewtabInternetExplorWindow UINewtabInternetExplorWindow
        {
            get
            {
                if ((this.mUINewtabInternetExplorWindow == null))
                {
                    this.mUINewtabInternetExplorWindow = new UINewtabInternetExplorWindow();
                }
                return this.mUINewtabInternetExplorWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private UIBingInternetExplorerWindow mUIBingInternetExplorerWindow;
        
        private UINewtabInternetExplorWindow mUINewtabInternetExplorWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://tailspinpaasdeploy.azurewebsites.net/' using new browser instance
        /// </summary>
        public string UIBingInternetExplorerWindowUrl = "http://tailspinpaasdeploy.azurewebsites.net/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'about:Tabs' using new browser instance
        /// </summary>
        public string UINewtabInternetExplorWindowUrl = "about:Tabs";
        
        /// <summary>
        /// Type 'http{RShiftKey}://tailspinpaasdeploy.azurewebsites' in text box
        /// </summary>
        public string UIItemEditSendKeys = "http{RShiftKey}://tailspinpaasdeploy.azurewebsites";
        
        /// <summary>
        /// Type '.net{Enter}' in text box
        /// </summary>
        public string UIItemEditSendKeys1 = ".net{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIBingInternetExplorerWindow : BrowserWindow
    {
        
        public UIBingInternetExplorerWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Bing";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Bing");
            this.WindowTitles.Add("Home - Tailspin Toys");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomeTailspinToysDocument UIHomeTailspinToysDocument
        {
            get
            {
                if ((this.mUIHomeTailspinToysDocument == null))
                {
                    this.mUIHomeTailspinToysDocument = new UIHomeTailspinToysDocument(this);
                }
                return this.mUIHomeTailspinToysDocument;
            }
        }
        
        public UIHomeTailspinToysInteTitleBar UIHomeTailspinToysInteTitleBar
        {
            get
            {
                if ((this.mUIHomeTailspinToysInteTitleBar == null))
                {
                    this.mUIHomeTailspinToysInteTitleBar = new UIHomeTailspinToysInteTitleBar(this);
                }
                return this.mUIHomeTailspinToysInteTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIHomeTailspinToysDocument mUIHomeTailspinToysDocument;
        
        private UIHomeTailspinToysInteTitleBar mUIHomeTailspinToysInteTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomeTailspinToysDocument : HtmlDocument
    {
        
        public UIHomeTailspinToysDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home - Tailspin Toys";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://tailspinpaasdeploy.azurewebsites.net/";
            this.WindowTitles.Add("Home - Tailspin Toys");
            #endregion
        }
        
        #region Properties
        public UIModelAirplanesCustom UIModelAirplanesCustom
        {
            get
            {
                if ((this.mUIModelAirplanesCustom == null))
                {
                    this.mUIModelAirplanesCustom = new UIModelAirplanesCustom(this);
                }
                return this.mUIModelAirplanesCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIModelAirplanesCustom mUIModelAirplanesCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIModelAirplanesCustom : HtmlCustom
    {
        
        public UIModelAirplanesCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "LI";
            this.SearchProperties["Id"] = "model";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"model\"";
            this.FilterProperties["InnerText"] = "Model Airplanes";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Home - Tailspin Toys");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIModelAirplanesHyperlink
        {
            get
            {
                if ((this.mUIModelAirplanesHyperlink == null))
                {
                    this.mUIModelAirplanesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIModelAirplanesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIModelAirplanesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIModelAirplanesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIModelAirplanesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Model Airplanes";
                    this.mUIModelAirplanesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIModelAirplanesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Browse Model Airplanes";
                    this.mUIModelAirplanesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://tailspinpaasdeploy.azurewebsites.net/?slug=model";
                    this.mUIModelAirplanesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIModelAirplanesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Browse Model Airplanes\" href=\"/?s";
                    this.mUIModelAirplanesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIModelAirplanesHyperlink.WindowTitles.Add("Home - Tailspin Toys");
                    #endregion
                }
                return this.mUIModelAirplanesHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIModelAirplanesHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomeTailspinToysInteTitleBar : WinTitleBar
    {
        
        public UIHomeTailspinToysInteTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Home - Tailspin Toys");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Home - Tailspin Toys");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINewtabInternetExplorWindow : BrowserWindow
    {
        
        public UINewtabInternetExplorWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "New tab";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIAddressandsearchusinWindow UIAddressandsearchusinWindow
        {
            get
            {
                if ((this.mUIAddressandsearchusinWindow == null))
                {
                    this.mUIAddressandsearchusinWindow = new UIAddressandsearchusinWindow(this);
                }
                return this.mUIAddressandsearchusinWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIAddressandsearchusinWindow mUIAddressandsearchusinWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAddressandsearchusinWindow : WinWindow
    {
        
        public UIAddressandsearchusinWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Address and search using Bing";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchusinEdit
        {
            get
            {
                if ((this.mUIAddressandsearchusinEdit == null))
                {
                    this.mUIAddressandsearchusinEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchusinEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search using Bing";
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIAddressandsearchusinEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchusinEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Address and search using Bing";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Edit";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
}
